# Generated by Django 5.0 on 2023-12-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='appicon',
            field=models.ImageField(default=True, upload_to='icon/'),
        ),
    ]
