# Generated by Django 5.0 on 2023-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_app_appicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.CharField(choices=[('Social', 'Social'), ('Finance', 'Finance'), ('Shopping', 'Shopping'), ('Communication', 'Communication'), ('Travel', 'Travel'), ('Entrainment', 'Entrainment'), ('Productivity', 'Productivity'), ('Music', 'Music')], max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='subcategory',
            field=models.CharField(choices=[('Network', 'Network'), ('Digital', 'Digital'), ('Messaging', 'Messaging'), ('Audio', 'Audio'), ('Marketplace', 'Marketplace'), ('Streaming', 'Streaming'), ('Loans', 'Loans'), ('Sharing', 'Sharing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
